/**
 * css.ts — emits `tokens.css`: the engine-neutral exchange layer.
 *
 * Produces `:root` (light) and `[data-theme="dark"]` blocks of `--md-sys-*`
 * custom properties. Both vanilla-extract and Tailwind read these same vars,
 * so the styling engine is just a different authoring layer over one runtime.
 */
import type { Tokens } from '../types';
import { kebab, TYPESCALE_PROPS } from './shared';

const PREFIX = '--md-sys';

function colorVars(tokens: Tokens, mode: 'light' | 'dark'): string[] {
  return Object.entries(tokens.sys.color).map(
    ([role, value]) => `  ${PREFIX}-color-${kebab(role)}: ${value[mode]};`,
  );
}

function staticVars(tokens: Tokens): string[] {
  const lines: string[] = [];

  for (const [role, v] of Object.entries(tokens.sys.shape)) {
    lines.push(`  ${PREFIX}-shape-${kebab(role)}: ${v};`);
  }
  for (const [role, v] of Object.entries(tokens.sys.elevation)) {
    lines.push(`  ${PREFIX}-elevation-${kebab(role)}: ${v};`);
  }
  for (const [role, v] of Object.entries(tokens.sys.state)) {
    lines.push(`  ${PREFIX}-state-${kebab(role)}: ${v};`);
  }
  for (const [role, props] of Object.entries(tokens.sys.typescale)) {
    for (const [key, suffix] of TYPESCALE_PROPS) {
      lines.push(`  ${PREFIX}-typescale-${kebab(role)}-${suffix}: ${props[key]};`);
    }
  }
  for (const [role, v] of Object.entries(tokens.sys.motion.easing)) {
    lines.push(`  ${PREFIX}-motion-easing-${kebab(role)}: ${v};`);
  }
  for (const [role, v] of Object.entries(tokens.sys.motion.duration)) {
    lines.push(`  ${PREFIX}-motion-duration-${kebab(role)}: ${v};`);
  }
  return lines;
}

export function generateTokensCss(tokens: Tokens): string {
  const statics = staticVars(tokens).join('\n');
  return `/* AUTO-GENERATED by @otomatty/tokens. Do not edit by hand. */

:root {
${colorVars(tokens, 'light').join('\n')}

${statics}
}

[data-theme='dark'] {
${colorVars(tokens, 'dark').join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${colorVars(tokens, 'dark').join('\n')}
  }
}
`;
}
