/**
 * tailwind.ts — emits `theme.css`: the Tailwind v4 `@theme` preset.
 *
 * Tailwind v4 is CSS-first, so no JS preset is needed. We map the design tokens
 * onto Tailwind's `--color-*`, `--radius-*`, `--shadow-*`, `--ease-*`,
 * `--text-*` namespaces, sourcing values from the runtime `--md-sys-*` vars.
 *
 * Colors are emitted as bare `rgb(var(--md-sys-color-x))` (channel triple →
 * opaque rgb). Tailwind v4 does NOT substitute the v3 `<alpha-value>` placeholder
 * inside an `@theme` block, so embedding it would leave every `--color-*` as an
 * invalid color (breaking `bg-primary`, `text-on-primary`, …). v4 instead derives
 * opacity modifiers (`bg-primary/12`) via `color-mix()` off this bare value.
 */
import type { Tokens } from '../types';
import { kebab } from './shared';

export function generateTailwindTheme(tokens: Tokens): string {
  const colors = Object.keys(tokens.sys.color).map((role) => {
    const k = kebab(role);
    return `  --color-${k}: rgb(var(--md-sys-color-${k}));`;
  });

  const radius = Object.keys(tokens.sys.shape).map((role) => {
    const k = kebab(role);
    // `none` & `full` map to Tailwind's rounded-none / rounded-full implicitly,
    // but we expose explicit names too for clarity.
    return `  --radius-${k}: var(--md-sys-shape-${k});`;
  });

  const shadows = Object.keys(tokens.sys.elevation).map((role) => {
    const k = kebab(role);
    return `  --shadow-${k}: var(--md-sys-elevation-${k});`;
  });

  const easings = Object.keys(tokens.sys.motion.easing).map((role) => {
    const k = kebab(role);
    return `  --ease-${k}: var(--md-sys-motion-easing-${k});`;
  });

  // Typescale → Tailwind `text-<role>` utilities (font-size + line-height pair).
  const text = Object.keys(tokens.sys.typescale).map((role) => {
    const k = kebab(role);
    return (
      `  --text-${k}: var(--md-sys-typescale-${k}-size);\n` +
      `  --text-${k}--line-height: var(--md-sys-typescale-${k}-line-height);\n` +
      `  --text-${k}--letter-spacing: var(--md-sys-typescale-${k}-tracking);\n` +
      `  --text-${k}--font-weight: var(--md-sys-typescale-${k}-weight);`
    );
  });

  return `/* AUTO-GENERATED by @m3-baseui/tokens. Do not edit by hand. */
/*
 * Tailwind v4 theme preset. Import AFTER tokens.css so the --md-sys-* runtime
 * vars exist:
 *   @import '@m3-baseui/tokens/tokens.css';
 *   @import 'tailwindcss';
 *   @import '@m3-baseui/tokens/theme.css';
 */
@theme {
  /* ---- Color (channel-triple → rgb; opacity via color-mix in v4) ---- */
${colors.join('\n')}

  /* ---- Shape / radius ---- */
${radius.join('\n')}

  /* ---- Elevation / shadow ---- */
${shadows.join('\n')}

  /* ---- Motion / easing ---- */
${easings.join('\n')}

  /* ---- Typescale ---- */
${text.join('\n')}
}
`;
}
