/**
 * tailwind.ts — emits `theme.css`: the Tailwind v4 `@theme` preset.
 *
 * Tailwind v4 is CSS-first, so no JS preset is needed. We map the design tokens
 * onto Tailwind's `--color-*`, `--radius-*`, `--shadow-*`, `--ease-*`,
 * `--text-*` namespaces, sourcing values from the runtime `--md-sys-*` vars.
 *
 * Colors use `rgb(var(--md-sys-color-x) / <alpha-value>)` so opacity modifiers
 * (`bg-primary/12`) compose correctly off the channel-triple values.
 */
import type { Tokens } from '../types';
import { kebab } from './shared';

export function generateTailwindTheme(tokens: Tokens): string {
  const colors = Object.keys(tokens.sys.color).map((role) => {
    const k = kebab(role);
    return `  --color-${k}: rgb(var(--md-sys-color-${k}) / <alpha-value>);`;
  });

  const radius = Object.keys(tokens.sys.shape).map((role) => {
    const k = kebab(role);
    // `none` & `full` map to Tailwind's rounded-none / rounded-full implicitly,
    // but we expose explicit names too for clarity.
    return `  --radius-${k}: var(--md-sys-shape-${k});`;
  });

  const shadows = Object.keys(tokens.sys.elevation).map((role) => {
    const k = kebab(role);
    return `  --shadow-${k}: var(--md-sys-elevation-${k});`;
  });

  const easings = Object.keys(tokens.sys.motion.easing).map((role) => {
    const k = kebab(role);
    return `  --ease-${k}: var(--md-sys-motion-easing-${k});`;
  });

  // Typescale → Tailwind `text-<role>` utilities (font-size + line-height pair).
  const text = Object.keys(tokens.sys.typescale).map((role) => {
    const k = kebab(role);
    return (
      `  --text-${k}: var(--md-sys-typescale-${k}-size);\n` +
      `  --text-${k}--line-height: var(--md-sys-typescale-${k}-line-height);\n` +
      `  --text-${k}--letter-spacing: var(--md-sys-typescale-${k}-tracking);\n` +
      `  --text-${k}--font-weight: var(--md-sys-typescale-${k}-weight);`
    );
  });

  return `/* AUTO-GENERATED by @m3/tokens. Do not edit by hand. */
/*
 * Tailwind v4 theme preset. Import AFTER tokens.css so the --md-sys-* runtime
 * vars exist:
 *   @import '@m3/tokens/tokens.css';
 *   @import 'tailwindcss';
 *   @import '@m3/tokens/theme.css';
 */
@theme {
  /* ---- Color (channel-triple → rgb with alpha) ---- */
${colors.join('\n')}

  /* ---- Shape / radius ---- */
${radius.join('\n')}

  /* ---- Elevation / shadow ---- */
${shadows.join('\n')}

  /* ---- Motion / easing ---- */
${easings.join('\n')}

  /* ---- Typescale ---- */
${text.join('\n')}
}
`;
}
