/**
 * ve-contract.ts — emits `src/generated/contract.css.ts`.
 *
 * A vanilla-extract `createGlobalThemeContract` that maps typed accessors
 * (`vars.sys.color.primary`) onto the *same* `--md-sys-*` variables emitted in
 * tokens.css. Each leaf holds the variable name (without the leading `--`); the
 * mapper returns it verbatim so VE binds to the runtime values defined by
 * tokens.css / ThemeProvider instead of minting fresh hashed names.
 */
import type { Tokens } from '../types';
import { kebab, TYPESCALE_PROPS } from './shared';

const PREFIX = 'md-sys';

function indentObject(lines: string[], indent: number): string {
  const pad = '  '.repeat(indent);
  return lines.map((l) => pad + l).join('\n');
}

export function generateVeContract(tokens: Tokens): string {
  const colorLines = Object.keys(tokens.sys.color).map(
    (role) => `${role}: '${PREFIX}-color-${kebab(role)}',`,
  );

  const shapeLines = Object.keys(tokens.sys.shape).map(
    (role) => `${role}: '${PREFIX}-shape-${kebab(role)}',`,
  );
  const elevationLines = Object.keys(tokens.sys.elevation).map(
    (role) => `${role}: '${PREFIX}-elevation-${kebab(role)}',`,
  );
  const stateLines = Object.keys(tokens.sys.state).map(
    (role) => `${role}: '${PREFIX}-state-${kebab(role)}',`,
  );

  const typescaleLines = Object.keys(tokens.sys.typescale).map((role) => {
    const props = TYPESCALE_PROPS.map(
      ([key, suffix]) => `      ${key}: '${PREFIX}-typescale-${kebab(role)}-${suffix}',`,
    ).join('\n');
    return `${role}: {\n${props}\n    },`;
  });

  const easingLines = Object.keys(tokens.sys.motion.easing).map(
    (role) => `${role}: '${PREFIX}-motion-easing-${kebab(role)}',`,
  );
  const durationLines = Object.keys(tokens.sys.motion.duration).map(
    (role) => `${role}: '${PREFIX}-motion-duration-${kebab(role)}',`,
  );

  return `/* AUTO-GENERATED by @m3/tokens. Do not edit by hand. */
import { createGlobalThemeContract } from '@vanilla-extract/css';

/**
 * Typed accessors bound to the runtime --md-sys-* variables. Color values are
 * channel triples ("R G B"); wrap with rgb() at the use site, e.g.
 *   background: \`rgb(\${vars.sys.color.primary})\`
 */
export const vars = createGlobalThemeContract(
  {
    sys: {
      color: {
${indentObject(colorLines, 4)}
      },
      shape: {
${indentObject(shapeLines, 4)}
      },
      elevation: {
${indentObject(elevationLines, 4)}
      },
      state: {
${indentObject(stateLines, 4)}
      },
      typescale: {
        ${typescaleLines.join('\n        ')}
      },
      motion: {
        easing: {
${indentObject(easingLines, 5)}
        },
        duration: {
${indentObject(durationLines, 5)}
        },
      },
    },
  },
  (value) => value as string,
);
`;
}
