/**
 * Reads @material-symbols/svg-400 outlined glyphs and writes:
 *   src/generated/core.ts  — icons referenced by this repo (default entry)
 *   src/generated/all.ts   — full catalog (`@m3-baseui/icons/all`)
 *
 * Run: bun run scripts/gen-glyphs.ts  (from this package)
 */
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';

const require = createRequire(import.meta.url);
const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = join(pkgRoot, '../..');
const svgRoot = dirname(require.resolve('@material-symbols/svg-400/package.json'));
const outlinedDir = join(svgRoot, 'outlined');

const VIEW_BOX = '0 -960 960 960';
const ICON_ATTR_RE = /<(?:Icon|MdIcon)\b[^>]*?\bname=["']([a-z0-9_]+)["']/gs;
const ICON_EXPR_RE = /<(?:Icon|MdIcon)\b[^>]*\bname=\{([^}]+)\}/g;
const QUOTED_SNAKE_RE = /['"]([a-z][a-z0-9_]*)['"]/g;
const ICON_FIELD_RE = /\bicon:\s*['"]([a-z][a-z0-9_]*)['"]/g;
const SKIP_DIRS = new Set(['node_modules', 'dist', 'generated', '.git']);

/** Material Icons ligature names that Material Symbols SVG files renamed. */
const ALIASES: Record<string, string> = {
  expand_more: 'keyboard_arrow_down',
  expand_less: 'keyboard_arrow_up',
  local_offer: 'sell',
};

function parsePath(svg: string, file: string): string {
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  if (viewBox !== VIEW_BOX) {
    throw new Error(`${file}: unexpected viewBox ${viewBox}`);
  }
  const paths = [...svg.matchAll(/<path\b[^>]*\sd="([^"]+)"/g)].map((m) => m[1]!);
  if (paths.length !== 1 || !paths[0]) {
    throw new Error(`${file}: expected exactly one path, got ${paths.length}`);
  }
  return paths[0];
}

function walk(dir: string, acc: string[] = []): string[] {
  for (const ent of readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(ent.name)) continue;
    const p = join(dir, ent.name);
    if (ent.isDirectory()) {
      walk(p, acc);
    } else if (/\.(?:tsx|ts|astro)$/.test(ent.name) && !ent.name.endsWith('.d.ts')) {
      acc.push(p);
    }
  }
  return acc;
}

function usesM3Icon(src: string): boolean {
  return src.includes('@m3-baseui/icons') || /\bMdIcon\b/.test(src);
}

function glyph(source: Record<string, string>, name: string): string | undefined {
  return Object.hasOwn(source, name) ? source[name] : undefined;
}

function usedNames(catalog: Record<string, string>): Set<string> {
  const names = new Set<string>();
  for (const file of walk(join(repoRoot, 'examples')).concat(walk(join(pkgRoot, 'src')))) {
    const src = readFileSync(file, 'utf8');
    for (const m of src.matchAll(ICON_ATTR_RE)) {
      if (m[1]) names.add(m[1]);
    }
    for (const m of src.matchAll(ICON_EXPR_RE)) {
      for (const q of (m[1] ?? '').matchAll(QUOTED_SNAKE_RE)) {
        const name = q[1];
        if (name && glyph(catalog, name)) names.add(name);
      }
    }
    if (usesM3Icon(src)) {
      for (const m of src.matchAll(ICON_FIELD_RE)) {
        if (m[1]) names.add(m[1]);
      }
    }
  }
  return names;
}

function pick(source: Record<string, string>, names: Set<string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const name of names) {
    const d = glyph(source, name);
    if (d) out[name] = d;
  }
  return out;
}

function emitModule(
  relPath: string,
  regular: Record<string, string>,
  fill: Record<string, string>,
): void {
  const banner = `/**
 * GENERATED by scripts/gen-glyphs.ts from @material-symbols/svg-400.
 * Do not edit.
 *
 * Outlined Material Symbols at weight 400 (FILL 0 / FILL 1).
 * Apache-2.0 — https://github.com/google/material-design-icons
 */
`;
  const source = `${banner}export const ICON_VIEW_BOX = '${VIEW_BOX}';

export const regular: Record<string, string> = JSON.parse(
  ${JSON.stringify(JSON.stringify(regular))},
);

export const fill: Record<string, string> = JSON.parse(
  ${JSON.stringify(JSON.stringify(fill))},
);

export function getGlyph(name: string, filled = false): string | undefined {
  if (filled && Object.hasOwn(fill, name)) {
    return fill[name];
  }
  if (Object.hasOwn(regular, name)) {
    return regular[name];
  }
  return undefined;
}
`;
  const abs = join(pkgRoot, relPath);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, source, 'utf8');
  console.log(
    `  ${relPath} (${Object.keys(regular).length} regular, ${Object.keys(fill).length} fill, ${source.length} bytes)`,
  );
}

const regular: Record<string, string> = {};
const fill: Record<string, string> = {};

for (const file of readdirSync(outlinedDir)) {
  if (!file.endsWith('.svg')) continue;
  const d = parsePath(readFileSync(join(outlinedDir, file), 'utf8'), file);
  if (file.endsWith('-fill.svg')) {
    fill[file.slice(0, -'-fill.svg'.length)] = d;
  } else {
    regular[file.slice(0, -'.svg'.length)] = d;
  }
}

const names = Object.keys(regular);
if (names.length === 0) {
  throw new Error('no outlined glyphs found');
}

for (const [from, to] of Object.entries(ALIASES)) {
  if (!regular[from] && regular[to]) {
    regular[from] = regular[to]!;
    const fillPath = fill[to];
    if (fillPath) fill[from] = fillPath;
  }
}

const coreNames = usedNames(regular);
if (coreNames.size === 0) {
  throw new Error('no Icon/MdIcon names found in examples or this package');
}

const missing = [...coreNames].filter((n) => !glyph(regular, n)).sort();
if (missing.length > 0) {
  console.warn(`  skipping unknown names: ${missing.join(', ')}`);
}

const knownCore = new Set([...coreNames].filter((n) => glyph(regular, n)));
console.log(`@m3-baseui/icons — core set ${knownCore.size} / ${names.length} glyphs`);
emitModule('src/generated/core.ts', pick(regular, knownCore), pick(fill, knownCore));
emitModule('src/generated/all.ts', regular, fill);
